version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout # Lấy mã nguồn

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Tests
          command: echo "Tests are running... (No actual tests defined)"

      - run:
          name: Build Docker Image
          command: docker build -t my-node-app .

      - run:
          name: Run Application
          command: docker run -p 3000:3000 my-node-app
        
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo $aimabiettroi | docker login -u $tangkhanhdang --password-stdin
            docker tag my-node-app $DOCKERHUB_USERNAME/my-node-app:latest
            docker push $tangkhanhdang/my-node-app:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
