version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16 # Node.js image

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout # Pull mã nguồn

      - run:
          name: Install Dependencies
          command: npm install

      - setup_remote_docker:
          docker_layer_caching: true # Cho phép cache layer Docker để build nhanh hơn

      - run:
          name: Debug Docker
          command: |
            docker version
            docker info

      - run:
          name: Run Tests
          command: echo "Tests are running... (No actual tests defined)"

      - run:
          name: Build Docker Image
          command: docker build -t my-node-app .

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag my-node-app $DOCKER_USERNAME/my-node-app:latest
            docker push $DOCKER_USERNAME/my-node-app:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
