version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t tangkhanhdang/server_node:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo $aimabiettroi | docker login -u $tangkhanhdang --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker push tangkhanhdang/server_node:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
